clusters=A,B

A.bootstrap.servers=kafka-a1:9092,kafka-a2:9094,kafka-a3:9095
B.bootstrap.servers=kafka-b1:9096,kafka-b2:9097,kafka-b3:9098

A->B.enabled=true
A->B.topics=.*

replication.policy.class=org.apache.kafka.connect.mirror.IdentityReplicationPolicy